import { useEffect, useState } from "react";
import { assignDeviceTags, assignGroupDevices, createDeviceGroup, createDeviceTag, deleteDeviceGroup, deleteDeviceTag, getAssignedDeviceTags, getDeviceGroups, getDeviceTags, getGroupMembers, removeGroupDevice, updateDeviceGroup, updateDeviceTag } from "../../services/deviceService";

export default function DeviceOrganisationDialog({ projectId, devices, onClose, onChanged }) {
  const [groups, setGroups] = useState([]), [tags, setTags] = useState([]), [loading, setLoading] = useState(true);
  const [error, setError] = useState(""), [feedback, setFeedback] = useState("");
  const [groupName, setGroupName] = useState(""), [tagName, setTagName] = useState("");
  const [selectedGroup, setSelectedGroup] = useState(""), [selectedDevice, setSelectedDevice] = useState("");
  const [members, setMembers] = useState([]), [selectedTags, setSelectedTags] = useState([]);
  const [groupSearch, setGroupSearch] = useState(""), [tagSearch, setTagSearch] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const [g, t] = await Promise.all([getDeviceGroups(projectId), getDeviceTags(projectId)]); setGroups(g); setTags(t); } catch (e) { setError(e.message || "Unable to load device organisation data."); } finally { setLoading(false); } };
  // Organisation data is an external API resource keyed by project.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { load(); }, [projectId]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (!selectedDevice) { setSelectedTags([]); return; } getAssignedDeviceTags(projectId, selectedDevice).then(values => setSelectedTags(values.map(tag => tag.id))).catch(() => setSelectedTags([])); }, [projectId, selectedDevice]);
  async function run(action, message) { setError(""); try { await action(); setFeedback(message); await load(); onChanged(); } catch (e) { setError(e.message || "The organisation change could not be completed."); } }
  async function viewMembers(id) { setSelectedGroup(id); try { setMembers(await getGroupMembers(projectId, id)); } catch (e) { setError(e.message); } }
  const chosen = devices.find(device => device.deviceId === selectedDevice);
  return <div className="device-dialog-backdrop" role="presentation"><section className="device-dialog device-organisation-dialog" role="dialog" aria-modal="true" aria-labelledby="organisation-title">
    <header><div><p>Device organisation</p><h2 id="organisation-title">Groups and tags</h2></div><button aria-label="Close device organisation" onClick={onClose}>×</button></header>
    {loading ? <p role="status">Loading groups and tags…</p> : <>
      {error && <p className="device-form-error" role="alert">{error}</p>}{feedback && <p role="status">{feedback}</p>}
      <div className="organisation-grid"><section><h3>Groups</h3><form onSubmit={e => { e.preventDefault(); run(() => createDeviceGroup(projectId, { name: groupName, description: "" }), "Group created."); setGroupName(""); }}><label>Group name<input required maxLength="100" value={groupName} onChange={e => setGroupName(e.target.value)} /></label><button type="submit">Create group</button></form><label>Search groups<input type="search" value={groupSearch} onChange={e => setGroupSearch(e.target.value)} /></label>
        {groups.length === 0 ? <p>No groups have been created.</p> : <ul className="organisation-list">{groups.filter(group => group.name.toLowerCase().includes(groupSearch.toLowerCase())).map(group => <li key={group.id}><button onClick={() => viewMembers(group.id)}><strong>{group.name}</strong> <span>{group.memberCount} devices</span></button><button aria-label={`Rename ${group.name}`} onClick={() => { const name = window.prompt("New group name", group.name); if (name) run(() => updateDeviceGroup(projectId, group.id, { name, description: group.description || "" }), "Group updated."); }}>Edit</button><button aria-label={`Delete ${group.name}`} onClick={() => window.confirm(`Delete empty group ${group.name}?`) && run(() => deleteDeviceGroup(projectId, group.id), "Group deleted.")}>Delete</button></li>)}</ul>}
      </section><section><h3>Tags</h3><form onSubmit={e => { e.preventDefault(); run(() => createDeviceTag(projectId, { name: tagName, description: "" }), "Tag created."); setTagName(""); }}><label>Tag name<input required maxLength="100" value={tagName} onChange={e => setTagName(e.target.value)} /></label><button type="submit">Create tag</button></form><label>Search tags<input type="search" value={tagSearch} onChange={e => setTagSearch(e.target.value)} /></label>
        {tags.length === 0 ? <p>No tags have been created.</p> : <ul className="organisation-list">{tags.filter(tag => tag.name.toLowerCase().includes(tagSearch.toLowerCase())).map(tag => <li key={tag.id}><strong>{tag.name}</strong><button aria-label={`Rename ${tag.name}`} onClick={() => { const name = window.prompt("New tag name", tag.name); if (name) run(() => updateDeviceTag(projectId, tag.id, { name, description: tag.description || "" }), "Tag updated."); }}>Edit</button><button aria-label={`Delete ${tag.name}`} onClick={() => window.confirm(`Delete tag ${tag.name} and its assignments?`) && run(() => deleteDeviceTag(projectId, tag.id), "Tag deleted.")}>Delete</button></li>)}</ul>}
      </section></div>
      <section className="organisation-assignment"><h3>Assign devices</h3><label>Device<select value={selectedDevice} onChange={e => setSelectedDevice(e.target.value)}><option value="">Select a device</option>{devices.map(device => <option key={device.deviceId} value={device.deviceId}>{device.name}</option>)}</select></label><label>Group<select value={selectedGroup} onChange={e => viewMembers(e.target.value)}><option value="">Select a group</option>{groups.map(group => <option key={group.id} value={group.id}>{group.name}</option>)}</select></label><button disabled={!selectedDevice || !selectedGroup} onClick={() => run(() => assignGroupDevices(projectId, selectedGroup, [selectedDevice]), "Device assigned to group.")}>Assign to group</button>
        <fieldset><legend>Tags for {chosen?.name || "selected device"}</legend>{tags.map(tag => <label key={tag.id}><input type="checkbox" checked={selectedTags.includes(tag.id)} onChange={e => setSelectedTags(ids => e.target.checked ? [...ids, tag.id] : ids.filter(id => id !== tag.id))} />{tag.name}</label>)}</fieldset><button disabled={!selectedDevice} onClick={() => run(() => assignDeviceTags(projectId, selectedDevice, selectedTags), "Device tags updated.")}>Save tags</button>
        {selectedGroup && <div><h4>Group members</h4>{members.length === 0 ? <p>This group is empty.</p> : <ul>{members.map(member => <li key={member.deviceId}>{devices.find(d => d.deviceId === member.deviceId)?.name || member.deviceId}<button onClick={() => run(() => removeGroupDevice(projectId, selectedGroup, member.deviceId), "Device removed from group.")}>Remove</button></li>)}</ul>}</div>}
      </section></>}
  </section></div>;
}
