import { render,screen,waitFor } from "@testing-library/react"; import userEvent from "@testing-library/user-event"; import { beforeEach,describe,expect,it,vi } from "vitest";
import DeviceConfigurationDialog from "./DeviceConfigurationDialog"; import * as api from "../../services/deviceService";
vi.mock("../../services/deviceService",()=>({getDeviceConfiguration:vi.fn(),updateDeviceConfiguration:vi.fn(),getDeviceConfigurationHistory:vi.fn(),restoreDeviceConfiguration:vi.fn(),getDeviceConfigurationTemplates:vi.fn(),createDeviceConfigurationTemplate:vi.fn(),updateDeviceConfigurationTemplate:vi.fn(),applyDeviceConfigurationTemplate:vi.fn()}));
const device={deviceId:"11111111-1111-1111-1111-111111111111",name:"Alpha",active:true};
const configuration={deviceId:device.deviceId,pollingIntervalSeconds:60,heartbeatIntervalSeconds:30,metricsCollectionIntervalSeconds:60,environment:"DEVELOPMENT",apiEndpoint:"",loggingLevel:"INFO",tags:["edge"],version:2,updatedAt:"2026-08-16T10:00:00",updatedBy:"user-1"};
const version={...configuration,version:1,action:"UPDATED",changedFields:["pollingIntervalSeconds"],changedAt:"2026-08-15T10:00:00",changedBy:"user-1"};
function ready({history=[version],templates=[]}={}){api.getDeviceConfiguration.mockResolvedValue(configuration);api.getDeviceConfigurationHistory.mockResolvedValue(history);api.getDeviceConfigurationTemplates.mockResolvedValue(templates);}
describe("DeviceConfigurationDialog",()=>{beforeEach(()=>vi.clearAllMocks());
 it("renders loading, current configuration and history",async()=>{ready();render(<DeviceConfigurationDialog device={device} role="ADMIN" onClose={vi.fn()}/>);expect(screen.getByText("Loading configuration…")).toBeInTheDocument();expect(await screen.findByLabelText("Polling interval (seconds)")).toBeInTheDocument();expect(screen.getByText(/Version 1/)).toBeInTheDocument();expect(screen.getByText(/not automatically pushed/)).toBeInTheDocument();});
 it("validates intervals before saving",async()=>{ready();const u=userEvent.setup();render(<DeviceConfigurationDialog device={device} role="OPERATOR" onClose={vi.fn()}/>);const inputs=await screen.findAllByRole("spinbutton");await u.clear(inputs[0]);await u.type(inputs[0],"1");await u.click(screen.getByRole("button",{name:"Save Configuration"}));expect(screen.getByRole("alert")).toHaveTextContent("at least 5");expect(api.updateDeviceConfiguration).not.toHaveBeenCalled();});
 it("saves configuration and reloads",async()=>{ready();api.updateDeviceConfiguration.mockResolvedValue({...configuration,version:3});const u=userEvent.setup();render(<DeviceConfigurationDialog device={device} role="OPERATOR" onClose={vi.fn()}/>);await screen.findByLabelText("Polling interval (seconds)");await u.click(screen.getByRole("button",{name:"Save Configuration"}));await waitFor(()=>expect(api.updateDeviceConfiguration).toHaveBeenCalledWith(device.deviceId,expect.objectContaining({tags:["edge"]})));expect(await screen.findByText("Configuration saved as a new version.")).toBeInTheDocument();});
 it("shows API load failure",async()=>{api.getDeviceConfiguration.mockRejectedValue(new Error("network"));api.getDeviceConfigurationHistory.mockResolvedValue([]);api.getDeviceConfigurationTemplates.mockResolvedValue([]);render(<DeviceConfigurationDialog device={device} role="ADMIN" onClose={vi.fn()}/>);expect(await screen.findByRole("alert")).toHaveTextContent("Unable to load");});
 it("applies selected template",async()=>{const template={...configuration,id:"22222222-2222-2222-2222-222222222222",name:"Production",description:"Defaults"};ready({templates:[template]});api.applyDeviceConfigurationTemplate.mockResolvedValue({});const u=userEvent.setup();render(<DeviceConfigurationDialog device={device} role="OPERATOR" onClose={vi.fn()}/>);await u.selectOptions(await screen.findByLabelText("Configuration template"),template.id);await u.click(screen.getByRole("button",{name:"Apply Template"}));await waitFor(()=>expect(api.applyDeviceConfigurationTemplate).toHaveBeenCalledWith(device.deviceId,template.id));});
 it("restores with confirmation",async()=>{ready();api.restoreDeviceConfiguration.mockResolvedValue({});vi.spyOn(window,"confirm").mockReturnValue(true);const u=userEvent.setup();render(<DeviceConfigurationDialog device={device} role="ADMIN" onClose={vi.fn()}/>);await u.click(await screen.findByRole("button",{name:"Restore"}));await waitFor(()=>expect(api.restoreDeviceConfiguration).toHaveBeenCalledWith(device.deviceId,1));});
 it("hides mutation controls for inactive devices",async()=>{ready();render(<DeviceConfigurationDialog device={{...device,active:false}} role="ADMIN" onClose={vi.fn()}/>);await screen.findByLabelText("Polling interval (seconds)");expect(screen.queryByRole("button",{name:"Save Configuration"})).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"Restore"})).not.toBeInTheDocument();});
 it("allows only admins to create templates",async()=>{ready();const first=render(<DeviceConfigurationDialog device={device} role="OPERATOR" onClose={vi.fn()}/>);await screen.findByLabelText("Polling interval (seconds)");expect(screen.queryByLabelText("Template name")).not.toBeInTheDocument();first.unmount();ready();render(<DeviceConfigurationDialog device={device} role="ADMIN" onClose={vi.fn()}/>);expect(await screen.findByLabelText("Template name")).toBeInTheDocument();});
});
